### ISSUE TITLE
OPTIMUM todo

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1324]
- [x] startup meeting oct 15th (st. louis). AV wants slides.
- [x] set up google mailing list
- [x] set up spreadsheet with contacts and detailed info on role
- [x] set up XNAT projects for all 5 sites (CAMH, Columbia, UPMC, UCLA, Wash U)
- [x] expect human phantom uploads to XNAT from all 5 sites week of October 23rd 
- [x] also expect fBIRN phantom uploads from all 5 sites week of October 23rd (ABCD sites just to upload a regular phantom)
- [x] Send other sites documentation on imaging-genetics.camh.ca
- [ ] obtain GE phantom protocol (we have Siemens)
- [x] program HCP lifespan faces task (E-Prime)
- [x] determine format and location of task data (decision: we want both edat2 file and txt file, and uploaded to XNAT resources)
- [x] RA training in mid Oct (naming, task, contacts, etc)
- [x] create SOP on general MR session (e.g., naming)
- [x] create SOP for RAs (i.e., amend SPINS example with task instructions from Colin)
- [x] update SOP with phantom naming convention
- [ ] determine exact expectations _from final protocol_ for scans, parameters, and order  - and set up QC pages accordingly
- [x] confirm there's no non-DICOM data coming in (e.g., distortion correction)
- [x] decide format of RA MRI scan notes (decision: will be form win central clinical REDCap database)
- [x] work with WashU to get API token to REDCap database to pull RA scan notes into Dashboard

**Comment by josephdviviano** [comment]
Participant IDs will consist of the following format:  Site ID followed by a 5 digit number (i.e., WU10000).
Site IDs will consist of the following:
o   St. Louis: WU
o   Los Angeles: LA
o   Toronto: UT
o   Columbia: CU
o   Pittsburgh: UP

**Comment by navonacalarco** [comment]
@josephdvivano, do you think it would be worthwhile to use the Informatics Platform naming convention (i.e., OBI convention) a bit more tightly, given that it's plausible we might move onto their system during this study's term?

**Comment by josephdviviano** [comment]
@navonacalarco I don't think we should make any moves that will break datman compatibility yet. When we come up with a migration strategy, it will be pretty much the same amount of work to migrate 20 studies and 21 studies, and the infromatics platform isn't quite set in stone AFAIK.

**Comment by navonacalarco** [comment]
Cool! I expected as much, just wanted to make sure. 

@DESm1th If it's relevant for your opinion, here's the official suggested XNAT standards for Research IT: http://neurowiki.camh.ca/mediawiki/index.php/XNATNamingConvention

**Comment by josephdviviano** [comment]
@navonacalarco @DESm1th to prevent naming errors with the RAs etc, I would suggest we use the exact same site IDs and participant IDs for the uploads to XNAT.

E.g.,: `OPT01_WU_WU10000_01_01`

I think this will minimise errors made by the RAs.

Then, after the study is totally done, we can just run a script that will map that format into something that is neuroinfromatics compatible (whatever form that happens to be in 3 years).

I suspect mapping a full study after completion will be the most sane and time-efficient way to do this. As it stands the neuroinfromatics platform offers us no benefit -- the benefit will be making it easier for us to share our information with other labs.

**Comment by DESm1th** [comment]
Hmm. We already seem not too far off their standards. None of our site codes seem to conflict with theirs (except we're using UT instead of UTO). And I think Joe is right about us having to do less work if we just port it all over after the fact.

**Comment by edickie** [comment]
I feel like this is probably the time to discuss any differences between
the two naming schemes and if anything can be done to inch us closer..

I was also wondering if we might want to consider putting dicoms and human
subjects in separate XNAT projects.. It might actually make our lives
easier..

On Sep 26, 2017 11:54, "Joseph Viviano" <notifications@github.com> wrote:

@navonacalarco <https://github.com/navonacalarco> I don't think we should
make any moves that will break datman compatibility yet. When we come up
with a migration strategy, it will be pretty much the same amount of work
to migrate 20 studies and 21 studies, and the infromatics platform isn't
quite set in stone AFAIK.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TIGRLab/admin/issues/1324#issuecomment-332244772>, or mute
the thread

**Comment by edickie** [comment]
I was acutally thinking of
1) adding a numeric index to the site id that would allow for it to be incremented upon scanner upgrades
(we know that the CU site will be getting an upgrade in the next year)

2) removing the site id from the subject feild..

E.g.,: OPT01_WU1_10000_01_01

**Comment by DESm1th** [comment]
I really like the idea of a numeric index on the site ID for scanner upgrades

**Comment by josephdviviano** [comment]
+1 on the number.

**Comment by josephdviviano** [comment]
OK I've sent a copy of the SOP to @edickie  and Aristotle.

**Comment by navonacalarco** [comment]
@josephdviviano wasn't sure if I should edit your list at the top of this issues, but based on meeting today, it sounds like we should add:

- [ ] create SOP for RAs (i.e., amend SPINS example with task instructions from Colin)
- [ ] adapt QC for multi-shell (RS and diffusion) as required
- [ ] confirm there's no non-DICOM data coming in (e.g., distortion correction)
- [ ] determine exact expectations _from final protocol_ for scans, parameters, and order  - and set up QC pages accordingly

**Comment by josephdviviano** [comment]
k

**Comment by navonacalarco** [comment]
@colinhawco @edickie @josephdviviano @DESm1th 

Hi guys, just wanted to check in about the status of our OPTIMUM stuff, and see if anything here is still outstanding, or if we can close. Thanks!
