### ISSUE TITLE
Move over to the CAMH network

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/admin#476]
I'll use this issue to coordinate the move over to the CAMH research VLAN. 

At the moment, outstanding issues related to this are: 
 - [x] #185 - Buy switch SFP 
 - [x] #446 - Migrate to the CAMH IPA server
 - [ ] #475 - Switch to using CAMH storage
 - [ ] #380 - "Howto" kimel binder
 - [x]  #500 - Switch to using SCC login names

**Comment by pipitone** [comment]
Other important issues to work out: 
- [ ] Move the workstations and servers over (physically at the switch) and reconfigure (this is also a good time to give our workstations [new names](https://mnx.io/blog/a-proper-server-naming-scheme/), e.g. `wrk1.kml.camhres.ca` or `wrk01-tigr.camhres.ca`). This includes VMs
- [ ] Special attention for the XNAT server, which could be switched over to use the CAMH external IP address (can be done anytime now)
- [ ] Set up a new login server, although it's not clear how we should do this given the firewall rules ;-)

**Comment by pipitone** [comment]
CAMH switch installed. Some issue with the SFPs still to sort out. I've configured `eth1` on the tigrsrv to operate on the CAMH network so we can use that to test once the switch is in order.

**Comment by pipitone** [comment]
Here's a plan for the move once the CAMH switch is up and running. I will continue to update this comment:

1. Move the workstations and servers over (physically at the switch) and reconfigure.
   1. Our block of IPs is 172.26.216.62-102, with netmask 255.255.254.0, gateway 172.26.216.1, DNS 172.28.216.52, and domain camhres.ca
   1. Ansible `common` hosts file will need to be updated. 
   1. Can also use this time to [rationalise our hostnames](https://mnx.io/blog/a-proper-server-naming-scheme/). For example: 
       - `wrk01-kml.camhres.ca` for a workstation
       - `vmm01-kml.camhres.ca` for a virtual machine host
       - `sto01-kml.camhres.ca` for file storage
       - `sge01-kml.camhres.ca` for gridengine host
       - `web01-kml.camhres.ca` for a web server
       - `srv01-kml.camhres.ca` for a generic server :D
   1. Once configured with the proper networking information, machines will likely need to be re-enrolled with IPA (may not need this). Use the `playbooks/ipa-enroll.yml` playbook.
1. Move the VMs over
1. Reconfigure the login server. Will need to be clever about routing to it.

**Comment by qchang** [comment]
Questions:
1, Do we have two groups of hosts to deal with, e.g. workstations and servers? Are they separated in playbooks?
2, Do you plan to change hostnames as the same time IPs are changed?

**Comment by pipitone** [comment]
Workstations and servers are separated in ansible (but only some servers are fully managed by ansible, e.g. `backup` and `srv-sge`). Workstations are in the "workstations" group. More on our ansible configuration: https://github.com/tigrlab/admin/wiki/ansible

As to changing the hostnames: not necessary if it complicates things. I've created [an updated `/etc/hosts` file template](https://github.com/TIGRLab/ansible-playbooks/blob/master/roles/common/templates/hosts.camh.j2) with possible new hostnames.

**Comment by qchang** [comment]
Changing host name would involve a two step process: first the old name has to be removed from enrollment as IPA client and then the new added. It is better to do this after the IP migration if desired.

**Comment by josephdviviano** [comment]
@pipitone thanks for doing the hosts file. 

@qchang I think we're going to want to move to these name changes, but there's no rush to do so. We can focus on the IP migration first.

**Comment by qchang** [comment]
172.25.9.201 ipaslave02.camhres.ca ipaslave02 would be changed to 
172.26.216.31 ipaslave02.camhres.ca ipaslave02 at the time when new /etc/hosts is implemented. Right?

**Comment by pipitone** [comment]
Yes. Can you explain how you arranged the vm to have an IP on the CAMH research vlan? We will need to do that with our other VMs.

**Comment by qchang** [comment]
vSwitch3 is used for 172.26.216/23, which is patched to the switch with ports configured for VLAN216 (port 46). 
Then ipaslave02 is configured with default gateway 172.26.216.1. Interfaces on 172.25.9/24 and 192.168.216/24 are not configured for default gateway but route to those are per their corresponding NICs.

I have added localadmin on ipaslave02 if you want to have a closer look. At this point ipaslave02 is also open to all IPA users to login.

**Comment by pipitone** [comment]
Okay that's great. So in my instructions ignore the bit about having SCC vlan IP addresses for esxi and VMs. ;-)

**Comment by josephdviviano** [comment]
@qchang @pipitone just for clarification:

the VMS will all lose access between our machines and 172.25.9/24, correct? so for each machine, I need to add 172.26.216/23 on a third ethernet port?

**Comment by josephdviviano** [comment]
Also, @qchang, I want to add our XNAT database to the 172.26.216/23 subnet in order to maintain connectivity between this machine and the TIGRLAB storage, as we discussed? If so, what IP should I give it on this subnet?

**Comment by josephdviviano** [comment]
@qchang disregard that last message -- I realize it was a dumb question :).

**Comment by josephdviviano** [comment]
For my own reference: how to change the IP of the ESXI server via the command line: http://www.yellow-bricks.com/2013/05/27/how-to-change-the-ip-address-of-esxi-through-the-commandline/

**Comment by josephdviviano** [comment]
We're done. Aside from a few naggers. But we're off the pet network and sylvain can have his damn switch.

**Comment by pipitone** [comment]
One last little thing would be to take esxi/vms off the RIC network so
that there are no more possible bridges between the two networks.

**Comment by josephdviviano** [comment]
did already

**Comment by pipitone** [comment]
YEEAAAAAAAAAAAAHHHHHHH

, Joseph Viviano wrote:
