### ISSUE TITLE
xbrain analysis todo

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#540]
- [x] find all behavioural data for DTI sample
  - [x] TASIT <- we're going to do our first analysis using this
  - [x] PANSS
  - [x] RMET
  - [x] demographics
- [x] calculate 'normal' scores in the healthy control group, find 8 (1/3) of the most normal subjects.
  - see `/mnt/tigrlab/jdv-lifeboat/projects/data/xbrain/assets/template.csv`
- [x] calculate mean brain activity within each ROI across these subjects to come up with template brain.
- [x] calculate correlation of each ROI in subject with the template.
- [x] use random forest to predict tasit score of held-out subjects.
- [ ] compare the utility of xbrain with classification using beta-weights.
- [ ] Look into using [`pymvpa`](http://www.pymvpa.org/modref.html#classifiers-and-errors) for other regression models if random forests appear to behave strangely

**Comment by josephdviviano** [comment]
Moved to private repo.
